name: JS Actions

on: [push]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # hello-action not yet created
    - name: hello-action
      uses: ./.github/actions/hello-world
